"""
Merge a Label Studio review-project export back into the original annotation JSON.

The review project tasks must contain data.source_task_id, generated by
label_studio/generate_review_project.py.

Example:
    python label_studio/merge_review_annotations.py \
      --original MapillaryDatasetL+R-Annoted.json \
      --review-export ReviewProjectExport.json \
      --out MapillaryDatasetL+R-Annoted-v2.json
"""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def extract_results(item: dict) -> tuple[str | None, str | None, list[dict]]:
    annotations = item.get("annotations") or []
    if not annotations:
        return None, None, []

    result = annotations[0].get("result") or []
    height = None
    confidence = None
    for entry in result:
        choices = (entry.get("value") or {}).get("choices") or []
        if not choices:
            continue
        if entry.get("from_name") == "height_class":
            height = choices[0]
        elif entry.get("from_name") == "confidence":
            confidence = choices[0]
    return height, confidence, result


def make_result(height: str, confidence: str) -> list[dict]:
    return [
        {
            "value": {"choices": [height]},
            "from_name": "height_class",
            "to_name": "original",
            "type": "choices",
            "origin": "manual",
        },
        {
            "value": {"choices": [confidence]},
            "from_name": "confidence",
            "to_name": "original",
            "type": "choices",
            "origin": "manual",
        },
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--original", type=Path, default=ROOT / "MapillaryDatasetL+R-Annoted.json")
    parser.add_argument("--review-export", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=ROOT / "MapillaryDatasetL+R-Annoted-v2.json")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    original = json.loads(args.original.read_text())
    review = json.loads(args.review_export.read_text())

    original_by_id = {int(item["id"]): item for item in original}
    updates = 0
    unchanged = 0
    skipped = 0

    for review_item in review:
        source_task_id = (review_item.get("data") or {}).get("source_task_id")
        if not source_task_id or int(source_task_id) not in original_by_id:
            skipped += 1
            continue

        height, confidence, _ = extract_results(review_item)
        if not height or not confidence:
            skipped += 1
            continue

        target = original_by_id[int(source_task_id)]
        old_height, old_confidence, _ = extract_results(target)
        if old_height == height and old_confidence == confidence:
            unchanged += 1
            continue

        if not target.get("annotations"):
            target["annotations"] = [{"result": []}]
        target["annotations"][0]["result"] = make_result(height, confidence)
        target.setdefault("meta", {})
        target["meta"]["review_updated"] = True
        target["meta"]["previous_height_class"] = old_height
        target["meta"]["previous_confidence"] = old_confidence
        updates += 1

    args.out.write_text(json.dumps(original, indent=2, ensure_ascii=False))
    print(f"Saved: {args.out}")
    print(f"Updated: {updates} | unchanged: {unchanged} | skipped: {skipped}")


if __name__ == "__main__":
    main()
